version: '3.9'
services:
  db:
    container_name: libDB
    image: postgres:latest
    environment:
      POSTGRES_DB: lib
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    restart: always

  web:
    container_name: tomcat
    build: .
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - db